etn-ccis/blui-angular-cli-templates

- .circleci/config.yml
- Add deploy step in ci config for master branch
> Add publish step to ci

- src/app/auth-workflow/package.json
- src/app/auth-workflow/template/pages/home/home.component.scss
- src/app/blank/package.json
- src/app/blank/template/app.component.scss
- src/app/routing/package.json
- src/app/routing/template/pages/home/home.component.scss
Fixes #5 
- Sets all version numbers to 1.0.0 for initial release through CI
- Fix center text
> Center text, get ready for official release

- PUBLISHING.md
> Add PUBLISHING.md

- angular.json
- package.json
- src/app/auth-workflow/template-dependencies.json
- src/app/blank/template-dependencies.json
- src/app/routing/template-dependencies.json
- yarn.lock
Fixes #10 
- Make the fontface update that we were holding off on until closer to release.
> Update to latest theme and font packages

- package.json
- src/app/auth-workflow/CHANGELOG.md
- src/app/auth-workflow/README.md
- src/app/auth-workflow/package.json
- src/app/auth-workflow/template-dependencies.json
- src/app/blank/CHANGELOG.md
- src/app/blank/README.md
- src/app/blank/package.json
- src/app/blank/template-dependencies.json
- src/app/routing/CHANGELOG.md
- src/app/routing/README.md
- src/app/routing/package.json
- src/app/routing/template-dependencies.json
- yarn.lock
- Update dependencies and changelog
Waiting on https://github.com/pxblue/themes/pull/167 and circleci publishing for themes and
https://github.com/pxblue/angular-component-library/pull/245 & then merge to master for circleci publishing for components.
*NOTE: Will need to verify this is working correctly and re-run circleci after the themes and component packages are published.
> [NG-#6]Update dependencies and changelog

- src/app/routing/CHANGELOG.md
- src/app/routing/package.json
- Routing Template needs version increase because `color=primary` was added to the appbar in prior PR.
> Bump up version

- src/app/auth-workflow/CHANGELOG.md
- src/app/blank/CHANGELOG.md
- src/app/routing/CHANGELOG.md
Fixes PXBLUE-1958
- Add package release dates to changelog
> Add package release dates to changelog

- .circleci/config.yml
- PUBLISHING.md
- src/app/auth-workflow/package.json
- src/app/blank/package.json
- src/app/routing/package.json
> Add publishing script

- src/app/auth-workflow/CHANGELOG.md
> Fix changelog

- src/app/auth-workflow/CHANGELOG.md
- src/app/auth-workflow/package.json
- src/app/auth-workflow/template/app.component.html
- src/app/auth-workflow/template/app.component.ts
- Move the template out of app.component.ts to its own file for auth workflow template
> Add app.component.html for auth template

- .circleci/config.yml
- src/app/auth-workflow/CHANGELOG.md
- src/app/auth-workflow/package.json
- src/app/auth-workflow/template-dependencies.json
- src/app/blank/CHANGELOG.md
- src/app/blank/package.json
- src/app/blank/template-dependencies.json
- src/app/routing/CHANGELOG.md
- src/app/routing/package.json
- src/app/routing/template-dependencies.json
- Update angular-templates to use latest pxb dependencies and integrate tag script.
> Update dependencies, get ready to use tag script

- src/app/auth-workflow/template/app.module.ts
- src/app/blank/template/app.module.ts
- src/app/routing/template/app.module.ts
> Add license info

- src/app/auth-workflow/CHANGELOG.md
- src/app/auth-workflow/package.json
- src/app/blank/CHANGELOG.md
- src/app/blank/package.json
- src/app/routing/CHANGELOG.md
- src/app/routing/package.json
> Update versions, get ready to publish

- src/app/auth-workflow/CHANGELOG.md
- src/app/blank/CHANGELOG.md
- src/app/routing/CHANGELOG.md
> Update changelog dates

- src/app/auth-workflow/package.json
- src/app/blank/package.json
- src/app/routing/package.json
> Remove the beta version

- src/app/auth-workflow/CHANGELOG.md
- src/app/auth-workflow/package.json
- src/app/blank/CHANGELOG.md
- src/app/blank/package.json
- src/app/routing/CHANGELOG.md
- src/app/routing/package.json
- Prepare to publish latest templates
> Prepare to publish

- .github/workflows/pr-comment.yml
- CODEOWNERS
- LICENSES.json
- README.md
- src/app/auth-workflow/package.json
- src/app/auth-workflow/template/pages/home/home.component.html
- src/app/blank/package.json
- src/app/blank/template/pages/home/home.component.html
- src/app/routing/package.json
- src/app/routing/template/pages/home/home.component.html
- Updated all links to their GHE equivalences
- Updated Codeowners
> Update codeowners and GHE links

- src/app/auth-workflow/template-dependencies.json
- src/app/blank/template-dependencies.json
- src/app/routing/template-dependencies.json
- yarn.lock
Fixes # Updated angular 15 dependencies files.
- 
- 
- 
-
- 
-
> migrate to ng15 dependencies updated

- src/app/auth-workflow/template-dependencies.json
Fixes # updated the angular workflow version.
- 
- 
- 
-
- 
-
> updated the angular workflow version

- src/app/auth-workflow/template/pages/home/home.component.html
- src/app/blank/template/pages/home/home.component.html
- src/app/routing/template/pages/home/home.component.html
- update links on home pages for https://github.com/etn-ccis/blui-angular-cli-templates/pull/94
- 
- 
-
- 
-
> update links to github page

- src/app/auth-workflow/template/navigation/user-menu/user-menu.component.ts
- src/app/auth-workflow/template/pages/home/home.component.html
- src/app/blank/template/pages/home/home.component.html
- src/app/routing/template/pages/home/home.component.html
- yarn.lock
Fixes # mobile logout issue is fixed.
- 
- 
- 
-
- 
-
> mobile logout issue is fixed
